
#include "MRTC.h"

class CRegisterGameWorld
{
public:
	CRegisterGameWorld()
	{

		// Game World
#ifdef PLATFORM_XBOX1
		MRTC_REFERENCE(CMWnd_XBoxLive);
		MRTC_REFERENCE(CMWnd_CubeMenu_SaveProfile);
		MRTC_REFERENCE(CMWnd_CubeMenu_ReturnBack);
		MRTC_REFERENCE(CMWnd_CubeMenu_Live_Message);
		MRTC_REFERENCE(CMWnd_CubeMenu_Live_Account);
		MRTC_REFERENCE(CMWnd_CubeMenu_Live_Login);
		MRTC_REFERENCE(CMWnd_CubeMenu_Live_PassCode);
		MRTC_REFERENCE(CMWnd_CubeMenu_Live_UpdateContentList);
		MRTC_REFERENCE(CMWnd_CubeMenu_Live_Content);
		MRTC_REFERENCE(CMWnd_CubeMenu_Live_DownloadContent);
		MRTC_REFERENCE(CMWnd_CubeMenu_Friends);
		MRTC_REFERENCE(CMWnd_CubeMenu_Friends_TakeAction);
#endif

		MRTC_REFERENCE(CMWnd_ModButton);
		MRTC_REFERENCE(CMWnd_CubeButton);
		MRTC_REFERENCE(CMWnd_CubeOptionButton);
		MRTC_REFERENCE(CMWnd_CubeText);
		MRTC_REFERENCE(CMWnd_CubeMeter);
		MRTC_REFERENCE(CMWnd_CubeOptionMeter);
		MRTC_REFERENCE(CMWnd_CubeLayout);
		MRTC_REFERENCE(CMWnd_CubeRgn);
		MRTC_REFERENCE(CMWnd_CubeSecondaryRect);
		MRTC_REFERENCE(CMWnd_ModInfoScreen);
		MRTC_REFERENCE(CMWnd_ModEdit);
		MRTC_REFERENCE(CMWnd_ModText);
		MRTC_REFERENCE(CMWnd_ModTexture);
		MRTC_REFERENCE(CMWnd_ModOptionBox);
//		MRTC_REFERENCE(CMWnd_ModInvObject);
		MRTC_REFERENCE(CMWnd_ModInvSquare);
		MRTC_REFERENCE(CMWnd_ModFrame);
		MRTC_REFERENCE(CMWnd_ModChainFrame);
		MRTC_REFERENCE(CMWnd_ModPlaneFrame);
		MRTC_REFERENCE(CMWnd_ModBitmap);
		MRTC_REFERENCE(CMWnd_L2Client);
		MRTC_REFERENCE(CMWnd_L2ClientContainer);
		MRTC_REFERENCE(CMWnd_List2);
		MRTC_REFERENCE(CWClient_Mod);
		MRTC_REFERENCE(CWClient_P6);
		MRTC_REFERENCE(CMWnd_ModSelectClass);
		MRTC_REFERENCE(CMWnd_ModSelectTeam);
		MRTC_REFERENCE(CMWnd_ModLoot_P6);
		MRTC_REFERENCE(CMWnd_CharacterList);
		MRTC_REFERENCE(CMWnd_LootList);
		MRTC_REFERENCE(CMWnd_TeamList);
		MRTC_REFERENCE(CMWnd_ModBriefing);
		MRTC_REFERENCE(CMWnd_ModDialogue);
		MRTC_REFERENCE(CMWnd_ModTelephone);
		MRTC_REFERENCE(CMWnd_CubeIngameScreen);
		MRTC_REFERENCE(CMWnd_CubeCommonLayout);
		MRTC_REFERENCE(CMWnd_Mission_Objectives);
		MRTC_REFERENCE(CMWnd_Mission_Inventory);
		MRTC_REFERENCE(CMWnd_Mission_Collectibles);
		MRTC_REFERENCE(CMWnd_Mission_Map);
		MRTC_REFERENCE(CMWnd_ModMissionMap);
		MRTC_REFERENCE(CWFrontEnd_Mod);
		MRTC_REFERENCE(CWFrontEnd_P6);
		MRTC_REFERENCE(CMWnd_ModMenu);
		MRTC_REFERENCE(CMWnd_Timed);
		MRTC_REFERENCE(CMWnd_Random);
		MRTC_REFERENCE(CMWnd_CenterImage);
		MRTC_REFERENCE(CMWnd_CubeMenu);
		MRTC_REFERENCE(CMWnd_CubeMenu_Fork);
		MRTC_REFERENCE(CMWnd_CubeMenu_Select_Profile);
		MRTC_REFERENCE(CMWnd_CubeMenu_ButtonConfig);
		MRTC_REFERENCE(CMWnd_CubeMenu_VideoSelection);
		MRTC_REFERENCE(CMWnd_CubeMenu_TextInput);
		MRTC_REFERENCE(CMWnd_CubeMenu_Select_SaveGame);
		MRTC_REFERENCE(CMWnd_CubeMenu_Extra_Content);
		MRTC_REFERENCE(CMWnd_CubeMenu_Extra_Content_View);
		MRTC_REFERENCE(CMWnd_View_Texture);
		MRTC_REFERENCE(CMWnd_CubeMenu_Extra_Content_ViewText);
		MRTC_REFERENCE(CMWnd_CubeMenu_ChooserBuilder);
		MRTC_REFERENCE(CMWnd_CubeMenu_Chooser);
		MRTC_REFERENCE(CMWnd_CubeMenu_NewGame);
		MRTC_REFERENCE(CMWnd_CubeMenu_Controller);
		MRTC_REFERENCE(CMWnd_ModGameMenu);
		MRTC_REFERENCE(CMWnd_CubeMenu_PuffTris);
		MRTC_REFERENCE(CMWnd_CubeMenu_LoadMap);
		MRTC_REFERENCE(CMWnd_CubeMenu_LoadScriptLayer);
		MRTC_REFERENCE(CMWnd_CubeMenu_Inventory);
		MRTC_REFERENCE(CMWnd_CubeMenu_Main_P6);
		MRTC_REFERENCE(CMWnd_CubeMenu_Journal_P6);
		MRTC_REFERENCE(CMWnd_CubeMenu_WeaponMod);
//		MRTC_REFERENCE(CMWnd_CubeMenu_Trading);
		MRTC_REFERENCE(CMWnd_ModTrading_P6);
		MRTC_REFERENCE(CMWnd_CubeMenu_Multiplayer_SelectMap);
		MRTC_REFERENCE(CMWnd_CubeMenu_Multiplayer_SelectServerList);
		MRTC_REFERENCE(CMWnd_CubeMenu_Multiplayer_SelectServerList_P6);
		MRTC_REFERENCE(CMWnd_CubeMenu_Multiplayer_PostGameLobby);
		MRTC_REFERENCE(CMWnd_CubeMenu_Multiplayer_StartGame);
		MRTC_REFERENCE(CMWnd_CubeMenu_Multiplayer_SelectGameMode);
		MRTC_REFERENCE(CMWnd_CubeMenu_Multiplayer_Search);
		MRTC_REFERENCE(CMWnd_CubeMenu_Multiplayer_Leaderboard);
		MRTC_REFERENCE(CMWnd_CubeMenu_Multiplayer_AdvancedSettings);
		MRTC_REFERENCE(CMWnd_CubeMenu_Mission_Items);
		MRTC_REFERENCE(CMWnd_CubeMenu_Controller2);
		MRTC_REFERENCE(CMWnd_CubeMenu_Map);
		MRTC_REFERENCE(CMWnd_CubeMenu_Darklings);
		MRTC_REFERENCE(CWServer_Mod);
		MRTC_REFERENCE(CWServer_P6);
		MRTC_REFERENCE(CXR_BlockNav);
		MRTC_REFERENCE(CXR_BlockNavSearcher_VPUDispatcher);
		MRTC_REFERENCE(CXR_BlockNavSearcher_Plain);
		MRTC_REFERENCE(CXR_BlockNav_Grid_GameWorld);
		MRTC_REFERENCE(CXBN_SearchResult);
		MRTC_REFERENCE(CWorldDataCore);
		MRTC_REFERENCE(CWRes_Anim);
//		MRTC_REFERENCE(CWRes_AnimList);
		//MRTC_REFERENCE(CWRes_AnimGraph);
		MRTC_REFERENCE(CWRes_AnimGraph2);
		//MRTC_REFERENCE(CWRes_AGAnimList);
		MRTC_REFERENCE(CWRes_DLL);
		MRTC_REFERENCE(CWRes_Registry);
		MRTC_REFERENCE(CWRes_Model);
		MRTC_REFERENCE(CWRes_Class);
		MRTC_REFERENCE(CWRes_Template);
		MRTC_REFERENCE(CWRes_Surface);
		MRTC_REFERENCE(CWRes_XFC);
		MRTC_REFERENCE(CWRes_Model_XMD);
		MRTC_REFERENCE(CWRes_Model_Custom);
		MRTC_REFERENCE(CWRes_Model_Custom_File);
		MRTC_REFERENCE(CWRes_Sound);
		MRTC_REFERENCE(CWRes_Wave);
		MRTC_REFERENCE(CWRes_Dialogue);
		MRTC_REFERENCE(CWRes_XWIndex);
		MRTC_REFERENCE(CWRes_Model_XW);
		MRTC_REFERENCE(CWRes_Model_XW2);
		MRTC_REFERENCE(CWRes_Model_XW3);
		MRTC_REFERENCE(CWRes_Model_XW4);
		MRTC_REFERENCE(CWRes_Model_Glass);
		MRTC_REFERENCE(CWRes_XWResource);
		MRTC_REFERENCE(CWRes_XWNavGrid);
		MRTC_REFERENCE(CWRes_XWNavGraph);
		MRTC_REFERENCE(CWRes_XW);
		MRTC_REFERENCE(CWRes_ObjectAttribs);
		MRTC_REFERENCE(CWRes_FacialSetup);
		MRTC_REFERENCE(CMapData);
		MRTC_REFERENCE(CWorld_ClientCore);
		MRTC_REFERENCE(CWorld_ServerCore);
		// MRTC_REFERENCE(CXR_NavGraph_Builder);
		MRTC_REFERENCE(CWorld_Navgraph_Pathfinder_AStar);
		MRTC_REFERENCE(CWorld_NavGraph_Path);
		MRTC_REFERENCE(CWireContainer);
		MRTC_REFERENCE(CDebugRenderContainer);
	}
};

CRegisterGameWorld g_GameWorldDyn;

